<a href="https://colab.research.google.com/github/ankitpredictsX/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [44]:
print("hello")

hello


In [45]:
import numpy as np

In [46]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [47]:
arr1 = np.arange(0,12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
x= np.array([1,2,3,4]).reshape(-1,1)
y=np.array([5,6,7,8])
print(1/x-y)

[[-4.         -5.         -6.         -7.        ]
 [-4.5        -5.5        -6.5        -7.5       ]
 [-4.66666667 -5.66666667 -6.66666667 -7.66666667]
 [-4.75       -5.75       -6.75       -7.75      ]]


In [49]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
a1=np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
print(a1,a2,a3,sep='\n')
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
8
int64
8


# Array Functions

In [53]:
a1 = np.random.random((3,3))
a1=np.round(a1*100)
print(a1)
print(np.max(a1,axis=1))
print(np.median(a1,axis=1))
print(np.log(a1))
print(np.sin(a1))
arr = np.array([1.2, 1.5, 1.8, -1.2, -1.8])

print(np.round(arr))#nearest Integer
print(np.floor(arr))#Returns the greatest integer less than or equal to the number
print(np.ceil(arr))#Returns the smallest integer greater than or equal to the number

[[56.  4. 16.]
 [88. 81.  3.]
 [69. 41. 40.]]
[56. 88. 69.]
[16. 81. 41.]
[[4.02535169 1.38629436 2.77258872]
 [4.47733681 4.39444915 1.09861229]
 [4.2341065  3.71357207 3.68887945]]
[[-0.521551   -0.7568025  -0.28790332]
 [ 0.0353983  -0.62988799  0.14112001]
 [-0.11478481 -0.15862267  0.74511316]]
[ 1.  2.  2. -1. -2.]
[ 1.  1.  1. -2. -2.]
[ 2.  2.  2. -1. -1.]


# Indexing and **Slicing**

In [54]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1[2:5:2])

[3 5]


In [55]:
a2= np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])
print(a2[0:2,1:3])
print(a2[1:,2:])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1:,1:3])

[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[ 5  6]
 [ 9 10]]


# **Reshaping**

In [56]:
print(np.transpose(a2))
print(a2.ravel())
print(a1.flatten())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]


# **Stacking**

In [57]:
a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
print(1,np.hstack((a4,a5)))#along the existing axis
print(2,np.vstack((a4,a5)))
print(3,np.stack((a4,a5),axis=1))#default axis=0
print(4,np.stack((a4,a5)))
print(5,np.dstack((a4,a5)))#dstack stacks arrays along the third axis (depth axis)
#np.dstack((a, b)).shape
# (m, n, 2)
result = np.column_stack((a4, a5))#same as np.hstack() for 2d
print(6,result)

1 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
2 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
3 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
4 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
5 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
6 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# **Spiliting**