<a href="https://colab.research.google.com/github/ankitpredictsX/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [20]:
print("hello")

hello


In [21]:
import numpy as np

In [22]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [23]:
arr1 = np.arange(0,12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
x= np.array([1,2,3,4]).reshape(-1,1)
y=np.array([5,6,7,8])
print(1/x-y)

[[-4.         -5.         -6.         -7.        ]
 [-4.5        -5.5        -6.5        -7.5       ]
 [-4.66666667 -5.66666667 -6.66666667 -7.66666667]
 [-4.75       -5.75       -6.75       -7.75      ]]


In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
a1=np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
print(a1,a2,a3,sep='\n')
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
8
int64
8


# Array Functions

In [29]:
a1 = np.random.random((3,3))
a1=np.round(a1*100)
print(a1)
print(np.max(a1,axis=1))
print(np.median(a1,axis=1))
print(np.log(a1))
print(np.sin(a1))
arr = np.array([1.2, 1.5, 1.8, -1.2, -1.8])

print(np.round(arr))#nearest Integer
print(np.floor(arr))#Returns the greatest integer less than or equal to the number
print(np.ceil(arr))#Returns the smallest integer greater than or equal to the number

[[63. 95. 54.]
 [59. 76. 31.]
 [45. 91. 72.]]
[95. 76. 91.]
[63. 59. 72.]
[[4.14313473 4.55387689 3.98898405]
 [4.07753744 4.33073334 3.4339872 ]
 [3.80666249 4.51085951 4.27666612]]
[[ 0.1673557   0.68326171 -0.55878905]
 [ 0.63673801  0.56610764 -0.40403765]
 [ 0.85090352  0.10598751  0.25382336]]
[ 1.  2.  2. -1. -2.]
[ 1.  1.  1. -2. -2.]
[ 2.  2.  2. -1. -1.]


# Indexing and **Slicing**

In [30]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1[2:5:2])

[3 5]


In [31]:
a2= np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])
print(a2[0:2,1:3])
print(a2[1:,2:])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1:,1:3])

[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[ 5  6]
 [ 9 10]]


# **Reshaping**

In [32]:
print(np.transpose(a2))
print(a2.ravel())
print(a1.flatten())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]


# **Stacking**

In [33]:
a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
print(1,np.hstack((a4,a5)))#along the existing axis
print(2,np.vstack((a4,a5)))
print(3,np.stack((a4,a5),axis=1))#default axis=0
print(4,np.stack((a4,a5)))
print(5,np.dstack((a4,a5)))#dstack stacks arrays along the third axis (depth axis)
#np.dstack((a, b)).shape
# (m, n, 2)
result = np.column_stack((a4, a5))#same as np.hstack() for 2d
print(6,result)

1 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
2 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
3 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
4 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
5 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
6 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# **Spiliting**

In [34]:
arr = np.array([1,2,3,4,5,6])
result = np.split(arr, 3)
print(result)
# split at specific Index
result = np.split(arr, [2, 4])
print(result)
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(np.hsplit(arr, 2))
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

print(np.vsplit(arr, 2))
arr = np.arange(24).reshape(2,2,6)

result = np.dsplit(arr, 3)
arr = np.arange(12).reshape(3,4)
np.array_split(arr, 2)# array_spilit allowed unequal division

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

# Numpy **Tricks**

In [35]:
#append
a= np.array([1,2,3,4,5,6])
np.append(a,11) #it is used to append the values along the mentioned axis, it flatten the array if axis is not mentioned

array([ 1,  2,  3,  4,  5,  6, 11])

In [36]:
#Concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(7,13).reshape(2,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
#unique
a = np.array([4, 2, 1, 2, 4, 3, 1, 4])
unique, index, inverse, counts = np.unique(
    a,
    return_index=True,
    return_inverse=True,
    return_counts=True
)
print("unique :", unique)
print("index  :", index)
print("inverse:", inverse)
print("counts :", counts)
print(unique[inverse])

unique : [1 2 3 4]
index  : [2 1 5 0]
inverse: [3 1 0 1 3 2 0 3]
counts : [2 2 1 3]
[4 2 1 2 4 3 1 4]


In [50]:
#expand_dims
np.expand_dims(a,axis=0)

array([[4, 2, 1, 2, 4, 3, 1, 4]])

In [48]:
#np.where()
np.where(a==1,5,1) #(condition,true,false), it return indexes of input array where the given condition is satisfied

array([1, 1, 5, 1, 1, 1, 5, 1])

In [55]:
#argmax-> returns only indexes , flatten the array when axis is not given
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))

0
2
[2 6 3 1 5 0 4 7]


In [56]:
#np.isin()
np.isin(a,[1,2])

array([False,  True,  True,  True, False, False,  True, False])

In [57]:
#flip
np.flip(a)

array([4, 1, 3, 4, 2, 1, 2, 4])

In [60]:
#put
np.put(a,[0,1],[8,9])# (array,index,replaced element), permanent changes
a

array([8, 9, 1, 2, 4, 3, 1, 4])

In [61]:
#delete
np.delete(a,[0,1])# (array,index), permanent changes

array([1, 2, 4, 3, 1, 4])

In [63]:
#clip
print(a)
np.clip(a,1,3)

[8 9 1 2 4 3 1 4]


array([3, 3, 1, 2, 3, 3, 1, 3])