<a href="https://colab.research.google.com/github/ankitpredictsX/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
arr1 = np.arange(0,12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
x= np.array([1,2,3,4]).reshape(-1,1)
y=np.array([5,6,7,8])
print(1/x-y)

[[-4.         -5.         -6.         -7.        ]
 [-4.5        -5.5        -6.5        -7.5       ]
 [-4.66666667 -5.66666667 -6.66666667 -7.66666667]
 [-4.75       -5.75       -6.75       -7.75      ]]


In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
a1=np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)
print(a1,a2,a3,sep='\n')
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.dtype)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
8
int64
8


# Array Functions

In [10]:
a1 = np.random.random((3,3))
a1=np.round(a1*100)
print(a1)
print(np.max(a1,axis=1))
print(np.median(a1,axis=1))
print(np.log(a1))
print(np.sin(a1))
arr = np.array([1.2, 1.5, 1.8, -1.2, -1.8])

print(np.round(arr))#nearest Integer
print(np.floor(arr))#Returns the greatest integer less than or equal to the number
print(np.ceil(arr))#Returns the smallest integer greater than or equal to the number

[[ 7. 76. 87.]
 [26. 25. 99.]
 [55. 24. 14.]]
[87. 99. 55.]
[76. 26. 24.]
[[1.94591015 4.33073334 4.46590812]
 [3.25809654 3.21887582 4.59511985]
 [4.00733319 3.17805383 2.63905733]]
[[ 0.6569866   0.56610764 -0.82181784]
 [ 0.76255845 -0.13235175 -0.99920683]
 [-0.99975517 -0.90557836  0.99060736]]
[ 1.  2.  2. -1. -2.]
[ 1.  1.  1. -2. -2.]
[ 2.  2.  2. -1. -1.]


# Indexing and **Slicing**

In [11]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1[2:5:2])

[3 5]


In [12]:
a2= np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])
print(a2[0:2,1:3])
print(a2[1:,2:])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1:,1:3])

[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[ 5  6]
 [ 9 10]]


# **Reshaping**

In [13]:
print(np.transpose(a2))
print(a2.ravel())
print(a1.flatten())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]


# **Stacking**

In [14]:
a4= np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
print(1,np.hstack((a4,a5)))#along the existing axis
print(2,np.vstack((a4,a5)))
print(3,np.stack((a4,a5),axis=1))#default axis=0
print(4,np.stack((a4,a5)))
print(5,np.dstack((a4,a5)))#dstack stacks arrays along the third axis (depth axis)
#np.dstack((a, b)).shape
# (m, n, 2)
result = np.column_stack((a4, a5))#same as np.hstack() for 2d
print(6,result)

1 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
2 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
3 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
4 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
5 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
6 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# **Spiliting**

In [15]:
arr = np.array([1,2,3,4,5,6])
result = np.split(arr, 3)
print(result)
# split at specific Index
result = np.split(arr, [2, 4])
print(result)
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(np.hsplit(arr, 2))
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

print(np.vsplit(arr, 2))
arr = np.arange(24).reshape(2,2,6)

result = np.dsplit(arr, 3)
arr = np.arange(12).reshape(3,4)
np.array_split(arr, 2)# array_spilit allowed unequal division

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

# Numpy **Tricks**

In [16]:
#append
a= np.array([1,2,3,4,5,6])
np.append(a,11) #it is used to append the values along the mentioned axis, it flatten the array if axis is not mentioned

array([ 1,  2,  3,  4,  5,  6, 11])

In [17]:
#Concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(7,13).reshape(2,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
#unique
a = np.array([4, 2, 1, 2, 4, 3, 1, 4])
unique, index, inverse, counts = np.unique(
    a,
    return_index=True,
    return_inverse=True,
    return_counts=True
)
print("unique :", unique)
print("index  :", index)
print("inverse:", inverse)
print("counts :", counts)
print(unique[inverse])

unique : [1 2 3 4]
index  : [2 1 5 0]
inverse: [3 1 0 1 3 2 0 3]
counts : [2 2 1 3]
[4 2 1 2 4 3 1 4]


In [19]:
#expand_dims
np.expand_dims(a,axis=0)

array([[4, 2, 1, 2, 4, 3, 1, 4]])

In [20]:
#np.where()
np.where(a==1,5,1) #(condition,true,false), it return indexes of input array where the given condition is satisfied

array([1, 1, 5, 1, 1, 1, 5, 1])

In [21]:
#argmax-> returns only indexes , flatten the array when axis is not given
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))

0
2
[2 6 3 1 5 0 4 7]


In [22]:
#np.isin()
np.isin(a,[1,2])

array([False,  True,  True,  True, False, False,  True, False])

In [23]:
#flip
np.flip(a)

array([4, 1, 3, 4, 2, 1, 2, 4])

In [24]:
#put
np.put(a,[0,1],[8,9])# (array,index,replaced element), permanent changes
a

array([8, 9, 1, 2, 4, 3, 1, 4])

In [25]:
#delete
np.delete(a,[0,1])# (array,index), permanent changes

array([1, 2, 4, 3, 1, 4])

In [26]:
#clip
print(a)
np.clip(a,1,3)

[8 9 1 2 4 3 1 4]


array([3, 3, 1, 2, 3, 3, 1, 3])

# Set **Operations**

In [27]:
#union1d
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#intersection1d
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.intersect1d(a,b)

array([3, 4, 5])

In [29]:
#setdiff1d->Elements in first array but not in second
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.setdiff1d(a,b)

array([1, 2])

In [30]:
#setxor1d()->Symmetric difference = elements in either array, but not both
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.setxor1d(a,b)

array([1, 2, 6, 7])

# Practice **Problems**

In [31]:
#Create a Null vector of size 10 but with 5th value which is 1
a = np.nan*np.empty(10)
a[5]=1
a

array([nan, nan, nan, nan, nan,  1., nan, nan, nan, nan])

In [32]:
#Wap to generate random array of shape(a,b) and print avg of the array
a, b = map(int, input("Enter rows and columns: ").split())

arr = np.random.random((a, b))

print(arr)
print("Average:", np.mean(arr))

Enter rows and columns: 5 4
[[0.51070423 0.65425243 0.47934459 0.52625055]
 [0.72844335 0.9953026  0.3222564  0.26213863]
 [0.77974159 0.71424239 0.54629889 0.25961586]
 [0.84834855 0.16190345 0.26466402 0.64314663]
 [0.06632061 0.63075902 0.09920109 0.73542099]]
Average: 0.5114177917268689


In [33]:
#wap to create a 2d array with one border and 0 inside
a,b= map(int,input("enter row and column").split())
d=np.ones((a,b))
d[1:-1,1:-1]=0
print(d)

enter row and column5 4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [34]:
#create a vector of size 10 with values ranging from 0 to 1 ,both excluded.
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [35]:
# create a 5x5 matrix with column  ranging from 0 to 4
print(np.tile(np.arange(0,5),(5,1)))
print(np.tile(np.arange(0,5),(5,1)).T)#transpose->row ranging
arr = np.zeros((5,5), dtype=int) + np.arange(5)
print(arr)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [36]:
# create a 5x5 matrix with row ranging from 0 to 4
print(np.tile(np.arange(5).reshape(5,1), (1,5)))
arr = np.zeros((5,5), dtype=int) + np.arange(5).reshape(-1,1)
print(arr)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [37]:
#Consider a array of shape(6,7,8), what is the index of 100th element
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

In [38]:
# you are given a space seperated list of no  , reverse the numpy array with type float
a = input("ENTER THE NO'S: ").strip().split()
print(np.array(a[::-1], dtype=float))

ENTER THE NO'S: 1 2 3 4 5 6 7 8 9
[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [39]:
# input arr=[1,2,3]
#output result =[1,1,1,2,2,2,3,3,3]
arr = np.array([1, 2, 3])

result = []
#extend expect a list or tupple
for x in arr:
    result.extend([x] * len(arr))

print(np.array(result))
arr = np.array([1,2,3])
#or
indexes = []

for i in range(len(arr)):
    indexes.extend([i] * len(arr))

print(indexes)
print(arr[indexes])

[1 1 1 2 2 2 3 3 3]
[0, 0, 0, 1, 1, 1, 2, 2, 2]
[1 1 1 2 2 2 3 3 3]


In [40]:
# fill the nan values of array with most common element in array
arr = np.array([[1,2,np.nan],
                [4,2,6],
                [np.nan,np.nan,5]])
d = {}
for i in arr.flatten():
    if not np.isnan(i):      # Skip NaN values
        if i in d:
            d[i] += 1
        else:
            d[i] = 1

most_common = sorted(d.items(), key=lambda x: x[1], reverse=True)[0][0]

arr[np.isnan(arr)] = most_common

print(arr)
#or
arr = np.array([[1,2,np.nan],
                [4,2,6],
                [np.nan,np.nan,5]])

# Remove NaNs
valid = arr[~np.isnan(arr)]

# Find unique values and counts
values, counts = np.unique(valid, return_counts=True)

# Most common value
most_common = values[np.argmax(counts)]

# Fill NaNs
arr[np.isnan(arr)] = most_common

print(arr)

[[1. 2. 2.]
 [4. 2. 6.]
 [2. 2. 5.]]
[[1. 2. 2.]
 [4. 2. 6.]
 [2. 2. 5.]]


In [44]:
#given 2 arrays x,y construct cauchy equation
x= np.array([1,2,3,4,5]).reshape(-1,1)
y=np.array([6,7,8,9,10])
print(1/(x-y))

[[-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]]


In [48]:
#Wap implementing broadcasting rule to check 2 array can be added or not taking 2 tuples as a input dimension
import numpy as np

def can_broadcast(s1, s2):
    r1 = s1[::-1]
    r2 = s2[::-1]

    # Zip stops at the shorter — that's correct per broadcasting rules
    result = []
    for i, j in zip(r1, r2):
        if i != j and i != 1 and j != 1:
            return False, None
        result.append(max(i, j))

    # Append remaining dims from the longer shape
    result.extend(r1[len(r2):])
    result.extend(r2[len(r1):])

    return True, tuple(result[::-1])


# ── Test ────────────────────────────────────────────────────
test_cases = [
    ((3, 4),    (3, 4)),
    ((5, 1),    (5,)),
    ((3, 1, 4), (3, 5, 4)),
    ((2, 3),    (4, 3)),
    ((1,),      (9, 9, 9)),
]

for s1, s2 in test_cases:
    ok, out_shape = can_broadcast(s1, s2)
    if ok:
        np_shape = np.broadcast_shapes(s1, s2)
        match = "✓" if out_shape == np_shape else "✗ mismatch"
        print(f"{str(s1):15} + {str(s2):15} → {str(out_shape):15} {match}")
    else:
        print(f"{str(s1):15} + {str(s2):15} → Cannot broadcast   ✗")

(3, 4)          + (3, 4)          → (3, 4)          ✓
(5, 1)          + (5,)            → (5, 5)          ✓
(3, 1, 4)       + (3, 5, 4)       → (3, 5, 4)       ✓
(2, 3)          + (4, 3)          → Cannot broadcast   ✗
(1,)            + (9, 9, 9)       → (9, 9, 9)       ✓


In [67]:
#create a random 3x4 matrix with value btw 0 to 100 and perform below task
#1->sort the matrix
arr= np.random.randint(0,100,(3,4))
print(arr)
print(np.sort(arr))

#2-> based on 2nd column
print(arr[arr[:,1].argsort()])

#3-> based on row max ascending
print(np.array(sorted(arr,key=lambda x:np.max(x))))
#sorted function always returns a list

#4-> based on clumn max indexing
print(arr[:,arr.argmax(axis=0).argsort()])

[[38 29 68 50]
 [26 30 30 19]
 [15 32 11 54]]
[[29 38 50 68]
 [19 26 30 30]
 [11 15 32 54]]
[[38 29 68 50]
 [26 30 30 19]
 [15 32 11 54]]
[[26 30 30 19]
 [15 32 11 54]
 [38 29 68 50]]
[[38 68 29 50]
 [26 30 30 19]
 [15 11 32 54]]


In [68]:
a = np.random.randint(0, 50, (3, 4))
b = np.random.randint(0, 50, (3, 4))

print("Array a:"); print(a)
print("Array b:"); print(b)

# ── Method 1: np.maximum (most direct) ─────────────────────
print("\nMethod 1 — np.maximum:")
print(np.maximum(a, b))

# ── Method 2: np.where ─────────────────────────────────────
print("\nMethod 2 — np.where:")
print(np.where(a > b, a, b))

# ── Method 3: stacking + max ───────────────────────────────
print("\nMethod 3 — np.stack + max:")
print(np.stack([a, b]).max(axis=0))

# ── Method 4: boolean masking ──────────────────────────────
print("\nMethod 4 — boolean masking:")
result = a.copy()
result[b > a] = b[b > a]
print(result)

Array a:
[[42 49 45 36]
 [35 23 44 37]
 [ 2  4 47 16]]
Array b:
[[ 0 25  7 22]
 [44 47 20 41]
 [ 8 29 46  6]]

Method 1 — np.maximum:
[[42 49 45 36]
 [44 47 44 41]
 [ 8 29 47 16]]

Method 2 — np.where:
[[42 49 45 36]
 [44 47 44 41]
 [ 8 29 47 16]]

Method 3 — np.stack + max:
[[42 49 45 36]
 [44 47 44 41]
 [ 8 29 47 16]]

Method 4 — boolean masking:
[[42 49 45 36]
 [44 47 44 41]
 [ 8 29 47 16]]


In [69]:
#input a = [1,2,3]
#output = [1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3]
a = np.array([1, 2, 3])

part1 = np.repeat(a, 3)        # [1,1,1, 2,2,2, 3,3,3]
part2 = np.tile(a, 3)          # [1,2,3, 1,2,3, 1,2,3]

result = np.concatenate([part1, part2])
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
